import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { ArrowRight, Globe, Linkedin, Mail, MapPin, QrCode } from "lucide-react";
import joeBlackPhoto from "@/assets/joe-black.jpg";
import { usePageMeta } from "@/hooks/usePageMeta";

/**
 * Digital business card at /joeblack. Rendered OUTSIDE <Layout> in App.tsx, so
 * it has no navbar: it is a standalone handoff page, not a marketing page.
 * The vCard and QR in public/ are generated by scripts/build-card-assets.mjs
 * (npm run card:assets). Change contact details there, not here.
 *
 * Email and LinkedIn only, no phone (Joe, 2026-08-04). His number stays off the
 * public site, which keeps this consistent with the sitewide no-messaging-CTA
 * rule from July.
 */

const EMAIL = "joe@dreamscope.win";
const LINKEDIN = "https://www.linkedin.com/in/joevblack";

/* Talks the card offers slides for, and only while they are current.
 *
 * There is no scheduler here on purpose: visibility is a pure function of the
 * date, so nothing can fail to fire and nothing can be left hanging. Outside
 * every window the block simply does not render.
 *
 * Dates are inclusive and are VIETNAM calendar days, not the viewer's. A
 * phone left on London time must not decide a Hanoi talk is over.
 */
const TALKS = [
  {
    from: "2026-09-19",
    to: "2026-09-21",
    title: "Symphony of Experience, Ha Noi",
    sub: "Slides from the talk",
    href: "/decks/hanoi-keynote.pdf",
  },
  {
    from: "2026-09-23",
    to: "2026-09-25",
    title: "She Loves Data",
    sub: "Slides from the talk",
    href: "/decks/she-loves-data.pdf",
  },
  {
    from: "2026-09-26",
    to: "2026-09-28",
    title: "Symphony of Experience, Ho Chi Minh City",
    sub: "Slides from the workshop",
    href: "/decks/hcmc-workshop.pdf",
  },
];

/** Today in Vietnam as YYYY-MM-DD, so the windows compare as plain strings. */
const vnToday = () =>
  new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Ho_Chi_Minh" }).format(new Date());

const currentTalk = (today = vnToday()) =>
  TALKS.find((t) => today >= t.from && today <= t.to) ?? null;

const css = `
  .jbc-page {
    --dark: #1E2B3A;
    --teal: #0C7C8A;
    --teal-light: #0E96A6;
    --cream: #F7F4EF;
    --sand: #EDE8E0;
    --warm-white: #FDFCFA;
    --body: #3A3A3A;
    --muted: #7A7A7A;

    font-family: 'DM Sans', sans-serif;
    color: var(--body);
    background: var(--dark);
    line-height: 1.6;
    min-height: 100dvh;
    -webkit-font-smoothing: antialiased;
    padding: 0 0 3rem;
  }
  .jbc-page * { box-sizing: border-box; }
  .jbc-page a { text-decoration: none; }

  .jbc-shell { max-width: 440px; margin: 0 auto; padding: 0 1.1rem; }

  /* HEADER */
  .jbc-head {
    position: relative;
    background: var(--dark);
    padding: 3rem 0 5.5rem;
    text-align: center;
    overflow: hidden;
  }
  .jbc-head::after {
    content: '';
    position: absolute;
    top: -55%; left: 50%; transform: translateX(-50%);
    width: 680px; height: 680px;
    background: radial-gradient(circle, rgba(12,124,138,0.30) 0%, transparent 68%);
    pointer-events: none;
  }
  .jbc-head-inner { position: relative; z-index: 1; }
  .jbc-avatar {
    width: 124px; height: 124px; margin: 0 auto 1.3rem;
    border-radius: 50%; overflow: hidden;
    border: 3px solid var(--teal-light);
    box-shadow: 0 18px 44px -18px rgba(0,0,0,0.75);
  }
  .jbc-avatar img { width: 100%; height: 100%; object-fit: cover; display: block; }
  .jbc-name {
    font-family: 'DM Serif Display', serif;
    font-size: 2.5rem; line-height: 1.1; color: #fff;
    margin: 0 0 0.55rem; letter-spacing: -0.01em;
  }
  .jbc-role {
    color: var(--teal-light); font-size: 0.94rem; font-weight: 500;
    letter-spacing: 0.09em; text-transform: uppercase; margin: 0 0 0.7rem;
  }
  /* Joe's operating line. It is the thing people should remember alongside
     the name, so it sits in the header rather than buried in the body. */
  .jbc-creed {
    font-family: 'DM Serif Display', serif;
    font-style: italic;
    font-size: 1.12rem; line-height: 1.35;
    color: rgba(255,255,255,0.9);
    max-width: 19ch; margin: 0 auto 0.95rem;
  }
  .jbc-place {
    display: inline-flex; align-items: center; gap: 0.4rem;
    color: rgba(255,255,255,0.62); font-size: 0.88rem; margin: 0;
  }
  .jbc-place svg { width: 14px; height: 14px; }

  /* CARD BODY */
  .jbc-body {
    position: relative; z-index: 2;
    margin-top: -3.6rem;
    background: var(--warm-white);
    border-radius: 18px;
    padding: 1.5rem 1.35rem 1.7rem;
    box-shadow: 0 26px 60px -24px rgba(0,0,0,0.55);
  }

  /* PRIMARY ACTION */
  .jbc-save {
    display: flex; align-items: center; justify-content: center; gap: 0.55rem;
    width: 100%; padding: 1.02rem 1rem;
    background: var(--teal); color: #fff;
    border-radius: 11px;
    font-size: 1.01rem; font-weight: 700; letter-spacing: 0.02em;
    transition: background 0.18s ease, transform 0.18s ease;
  }
  .jbc-save:hover { background: var(--teal-light); transform: translateY(-1px); }
  .jbc-save:active { transform: translateY(0); }
  .jbc-save svg { width: 19px; height: 19px; }
  .jbc-save-note {
    text-align: center; font-size: 0.78rem; color: var(--muted);
    margin: 0.6rem 0 0;
  }

  /* ICON ROW */
  .jbc-links {
    display: grid; grid-template-columns: repeat(3, 1fr); gap: 0.55rem;
    list-style: none; padding: 0; margin: 1.5rem 0 0;
  }
  .jbc-links a {
    display: flex; flex-direction: column; align-items: center; gap: 0.5rem;
    padding: 1.05rem 0.3rem;
    background: var(--cream); border: 1px solid var(--sand);
    border-radius: 11px; color: var(--dark);
    transition: background 0.18s ease, border-color 0.18s ease, transform 0.18s ease;
  }
  .jbc-links a:hover {
    background: #fff; border-color: var(--teal); transform: translateY(-2px);
  }
  .jbc-links svg { width: 22px; height: 22px; color: var(--teal); }
  .jbc-links span {
    font-size: 0.74rem; font-weight: 600; letter-spacing: 0.03em;
    color: var(--body); text-align: center; line-height: 1.2;
  }

  .jbc-rule { border: 0; border-top: 1px solid var(--sand); margin: 1.6rem 0; }

  /* WHAT I DO */
  .jbc-label {
    font-size: 0.7rem; font-weight: 700; letter-spacing: 0.13em;
    text-transform: uppercase; color: var(--muted); margin: 0 0 0.7rem;
  }
  /* Reads as a list without bullets: a thin teal rule marks each item. */
  .jbc-practice {
    font-size: 0.92rem;
    padding-left: 0.85rem;
    border-left: 2px solid var(--teal);
    margin-bottom: 1rem;
  }
  .jbc-practice:last-of-type { margin-bottom: 0; }
  .jbc-practice-name {
    display: block;
    color: var(--dark); font-weight: 700;
    font-size: 0.97rem; line-height: 1.35;
    margin-bottom: 0.1rem;
  }

  /* BRIEF CTA */
  .jbc-brief {
    display: flex; align-items: center; justify-content: space-between; gap: 1rem;
    margin-top: 1.6rem; padding: 1.05rem 1.15rem;
    background: var(--dark); border-radius: 12px;
    transition: transform 0.18s ease;
  }
  .jbc-brief:hover { transform: translateY(-2px); }
  .jbc-brief-title {
    display: block; color: #fff; font-weight: 700;
    font-size: 0.97rem; margin-bottom: 0.16rem;
  }
  .jbc-brief-sub {
    display: block; color: rgba(255,255,255,0.6); font-size: 0.81rem; line-height: 1.4;
  }
  .jbc-brief svg { width: 20px; height: 20px; color: var(--teal-light); flex-shrink: 0; }

  /* QR */
  .jbc-talk {
    display: flex; align-items: center; justify-content: space-between; gap: 0.9rem;
    background: var(--teal); color: #fff; border-radius: 12px;
    padding: 0.95rem 1.1rem; margin-bottom: 1.1rem;
    transition: transform 0.15s ease;
  }
  .jbc-talk:hover { transform: translateY(-2px); }
  .jbc-talk-title { display: block; font-weight: 700; font-size: 0.98rem; line-height: 1.3; }
  .jbc-talk-sub {
    display: block; font-size: 0.78rem; margin-top: 0.2rem; color: rgba(255,255,255,0.78);
  }
  .jbc-talk svg { width: 20px; height: 20px; flex-shrink: 0; }

  .jbc-qr-toggle {
    display: flex; align-items: center; justify-content: center; gap: 0.45rem;
    width: 100%; margin-top: 1rem; padding: 0.7rem;
    background: none; border: 1px solid var(--sand); border-radius: 10px;
    color: var(--muted); font-family: inherit; font-size: 0.82rem; font-weight: 600;
    cursor: pointer; transition: color 0.18s ease, border-color 0.18s ease;
  }
  .jbc-qr-toggle:hover { color: var(--teal); border-color: var(--teal); }
  .jbc-qr-toggle svg { width: 16px; height: 16px; }
  .jbc-qr-panel { margin-top: 0.9rem; text-align: center; }
  .jbc-qr-panel img {
    width: 190px; height: 190px; display: block; margin: 0 auto;
    padding: 0.6rem; background: #fff;
    border: 1px solid var(--sand); border-radius: 12px;
  }
  .jbc-qr-panel p { font-size: 0.78rem; color: var(--muted); margin: 0.65rem 0 0; }

  /* FOOTER */
  .jbc-foot {
    text-align: center; margin-top: 1.6rem;
    color: rgba(255,255,255,0.42); font-size: 0.76rem; line-height: 1.7;
  }
  .jbc-foot a { color: rgba(255,255,255,0.62); }
  .jbc-foot a:hover { color: #fff; }

  @media (max-width: 380px) {
    .jbc-name { font-size: 2.15rem; }
    .jbc-links { gap: 0.4rem; }
    .jbc-links span { font-size: 0.7rem; }
  }
`;

const Card = () => {
  const [showQr, setShowQr] = useState(false);
  const [talk, setTalk] = useState<(typeof TALKS)[number] | null>(null);

  // Fail closed. The date window opens the block, but it only renders once the
  // deck is confirmed present, so an unuploaded PDF hides the block instead of
  // handing the audience a 404.
  useEffect(() => {
    const t = currentTalk();
    if (!t) return;
    let live = true;
    fetch(t.href, { method: "HEAD" })
      .then((r) => {
        if (live && r.ok) setTalk(t);
      })
      .catch(() => {});
    return () => {
      live = false;
    };
  }, []);

  usePageMeta({
    title: "Joe Black | Dreamscope",
    description:
      "Founder of Dreamscope Consulting. Culture and operations for growing companies, and expert work trained into AI. Based in Ho Chi Minh City.",
    noindex: true,
  });

  useEffect(() => {
    const style = document.createElement("style");
    style.textContent = css;
    document.head.appendChild(style);

    return () => {
      document.head.removeChild(style);
    };
  }, []);

  return (
    <div className="jbc-page">
      <header className="jbc-head">
        <div className="jbc-head-inner">
          <div className="jbc-avatar">
            <img src={joeBlackPhoto} alt="Joe Black" />
          </div>
          <h1 className="jbc-name">Joe Black</h1>
          <p className="jbc-role">Founder, Dreamscope</p>
          <p className="jbc-creed">
            "Everything works better if people love what they do."
          </p>
          <p className="jbc-place">
            <MapPin aria-hidden="true" /> Ho Chi Minh City, Vietnam
          </p>
        </div>
      </header>

      <div className="jbc-shell">
        <div className="jbc-body">
          {/* No download attribute on purpose. With Content-Type text/vcard and
              no forced download, iOS Safari shows its native "Add to Contacts"
              preview instead of dumping the file into Files.app. */}
          <a className="jbc-save" href="/joeblack.vcf">
            <ArrowRight aria-hidden="true" /> Save my contact
          </a>
          <p className="jbc-save-note">Adds straight to your phone, photo and all.</p>

          {talk && (
            <a className="jbc-talk" href={talk.href} target="_blank" rel="noreferrer">
              <span>
                <span className="jbc-talk-title">{talk.sub}</span>
                <span className="jbc-talk-sub">{talk.title}</span>
              </span>
              <ArrowRight aria-hidden="true" />
            </a>
          )}

          <ul className="jbc-links">
            <li>
              <a href={`mailto:${EMAIL}`}>
                <Mail aria-hidden="true" />
                <span>Email</span>
              </a>
            </li>
            <li>
              <a href={LINKEDIN} target="_blank" rel="noreferrer">
                <Linkedin aria-hidden="true" />
                <span>LinkedIn</span>
              </a>
            </li>
            <li>
              <a href="/">
                <Globe aria-hidden="true" />
                <span>Website</span>
              </a>
            </li>
          </ul>

          <hr className="jbc-rule" />

          <p className="jbc-label">Two practices</p>
          <div className="jbc-practice">
            <span className="jbc-practice-name">Culture and operations</span>
            for companies growing faster than their systems can handle, built on
            what your own people already know is broken.
          </div>
          <div className="jbc-practice">
            <span className="jbc-practice-name">AI Maestro</span>
            where I take expert work and train AI to do it. Months of work
            becomes days.
          </div>

          <Link className="jbc-brief" to="/brief">
            <span>
              <span className="jbc-brief-title">Read the Brief</span>
              <span className="jbc-brief-sub">
                One per practice, 90 seconds each. Pick the one you came for.
              </span>
            </span>
            <ArrowRight aria-hidden="true" />
          </Link>

          <button
            type="button"
            className="jbc-qr-toggle"
            onClick={() => setShowQr((v) => !v)}
            aria-expanded={showQr}
          >
            <QrCode aria-hidden="true" />
            {showQr ? "Hide QR code" : "Show QR code to share this"}
          </button>

          {showQr && (
            <div className="jbc-qr-panel">
              <img
                src="/joeblack-qr.svg"
                alt="QR code linking to dreamscope.win/joeblack"
              />
              <p>dreamscope.win/joeblack</p>
            </div>
          )}
        </div>

        <p className="jbc-foot">
          Dreamscope Consulting
          <br />
          <a href={`mailto:${EMAIL}`}>{EMAIL}</a>
        </p>
      </div>
    </div>
  );
};

export default Card;
